language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "e6f9IQlkw5LL/GI83kiqH28neYKCSbl9jPDmNfV7SLC1gVlSXRYD4YdbxYmiJO3h6fdEP9mHozOF09rZAWg4300VIyn52bJqLMppRhuD+WetY4GYT97HB726ALof54iyC5z5RmrDCU27MiawyFz3rkH4qvr2wODRAIN/sgUUdBNLyicH3UOtr3mP9j1WY7UTDwEI5LYkvsQ/tMm/nXEFZC60hi9TgDBgUNAWgA+JU7TQZZnfDmSvwgkFYUyAx/gVAFkDSnD56ljy7zFOf51aZQYQbuT1DJkm6FyznW7ITTOGa33rtT73vUIuFKp5sCbE8ATrxJDWre+AiErlmF4FmYqE1F9RjDw+XwmC3OOp+gpKf/5WFkMejqzB3rV2/s7x9zr2P+Q/x7v/9dKrPm5lQiWU0ymFy4pteMOnFiXq7G6U2qDI7Zaf5ZvdQI+10ccD3D3qFAjE+PlJxxVOhwkd2vwbzGPZK+BWnwenTeB3vJTfc4WEsSaM93yxnZ7dVkYQYc6RPodDND1ekLZYiDb+zHFm/UvqEdcbJxJVlPp3bW3NH31WdCT9bCQ+vxEVWbr1raXoF/sdMBfr11C7vIb2CMTgw+47vR8iLis4fzPi+LUYb6TV7LbhkNPKbnuz0umEAgw69HcH2p2S+R+ALIAJtnW7m/dptfLoDaYRRJe0rkc="

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.language=java

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

