language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "WpTN6fPyVsEShLIzYw5pnBaZkmqDpTNUNgKneve0A5CVimnDxZE38TOqJyzakIpwgpKwLRuKmkB3eQ0Go7ZTo/3o0ezHOtv0h136+ISPe/hdrpitHA8YoKDnUMWnhIh/viRJxUJmIfzgzI6Gr486IymqrcC8YKJSOlBsw+ix3eb+Sfu+7Tg8Vi0UAtWiUN6qk4Z2238EFwMxqsGkL+UNJrN6X9mDNeHFp/hssAi24rSbo+ZYN6rQo/lSJAKnBqFkPKnVqG3VqIUwjrdhuc35tbOoIBnj/6ltlt4P6FCXExDmmxaWA+eebOO4yZowJIuyDNB87xmRk4nmjnFj0nW2LBOYcPAP7U05kxs6mkfymgP3OeLD7kXlrHUfxZPR9xEtPIM3ICoQifsHgVpqpjLJYmUMNM/5DBYmUwJZAHI3CPVwPt3kHbBrLiy95+3zfFVgUOVAS0BE83OsbQCdOVc4L7U9S/Vu9xcnio+T1ga1CoxaLS1f87vXBAd3vizmxKKo9JLAvi2RnkkRr8jkg6hdUDz6imb3uPLnUQ5gWi4UxuGpK4HhEdIaJ3Mp2p7RFSUZzEE5Q0LvFeAlNO38xjUhcYJ3PrBgb2fFqbWM7ITTLyhc6dNmHGuflxQ/tiew7JhJoMQvHJ0+lwft0HiZhJeKq9YFxUdLmkI4hxZFZ2HIFGA="

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.language=java

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

