language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "pIhbd5FHEGvL6eFrdVcxLL2OYcvIKlpFN6PSOB0uwLR0QYCERYXDSOpD5CG4OXh4jb8a+u8P7UNPIOTIqwGnnkVEe/GWny5EwgHjYpQq1H/Gn6peqoH1YXJ8jWshDnGUjNtLCfCICOjHsKjwPEVkN/nfOpOkDTms81p1J6lvNaC2bmVlqT15V/dw9uDF0wRQVPtmcSlCKGJKcl9V6BI2Ed+JWC01/VEzhlYnIyFt1H7NApIm6jO6ywfVf9mgEK+m1uIW5/P4JJFFtWMmO1TNQeeaHFHd2onCTpq+QEGMXrsnab+jb5I2kBkpv+K+NAktJgKMsQ4lGOETdNbsZS8x9W9sBlxM2w2c1OSgpIKbMhT5Ydvf92Vy5u7GiJIHVpwml04NzsE4Ao3pw2ZwZSv3yZvqAI1DvCzRqZdMLzmTgFgDG5ht/hhWHpH16TmGcraPMphL7piX9nOEhTsd3jYXQvIVp8y8GEvT7i4VE3ugzd2kDteVErvTVBx7LQaYIHl6nMb9l/pHl+BXvV3m0WFE0Ee+LGOOMmOLAPAmD0akG4hx10nWVxfeZ+AjC1aZoMavK6cpy2u2O4+ZFm4dzKu/V4dwavnX+HJmqt4Oa1SMGQCbj6bcSk8d2aXXk4+OQw0RfiuQ9R0UEiHr9OEK4zvYNHABm/wDOzhW0q5813G4rSY="

script:
  - mvn clean verify sonar:sonar -Dsonar.scm.disabled=true -Dsonar.language=java -Dsonar.projectKey=dernasherbrezon_8430ft_exporter

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

