language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "TdZHlkZQoxNRbkRP2tR6hvjYLYutfWAIF42su66TTV3dNof0k02xr1/Sc4dxDiJeaVTQIZHkfS4XFAhlqCNsTLbCtDA2e/Z5giEWrK8aK4E3vmMGE5zpZemcGXsDTN3ziRgtwBMPcGMpR7R/RZsgVTekqy1YarGP1/BPDs9xH4Ae2CjLOtHFXCHdcn9jIi006IXgN+6c9iQCmA40VnLNZGZR2mcWkc4xYpRNtUXgsN+fxq3TGpDYT5A40chmPJ4UtBJC+eNK97FiiuHXC8F5vwRjpu5IrC+2/t+u6rpDSxJVIswlCGKcgK6T1Q/Erfht+jW3ila9bJe8oCTwKfvXGF3HifKK3/Rr6SeLY8JnCpQNW70Em5k16iMupmaoEQ9VlP2B8zqOqUGEjUjZFu05VgBShIofc0UI4w7AC3g2LTIn9MZ+8JNBz9yLqT3uhZl0RuOCNeh06kqj6fkG3TH+VORAIOodS4bf/0OBhhRJoCv54VLeszjprV/gJvcYqj4jkJ55N/BeFDeTszzHyw6sF0U0w3mBaA474nfO1rOEFOtym92hNaeZECu85YdYi2+pgK2K3pDOQ5bfGxhq0Ea5MJSOhGR7kpaQ/TO18fX9dIWVSYrAWsYOUSWpF5qgw/qr8CI7tfE4SDYxjsbB3jJgfPobc7pO2Bi/+um4j4T1kdU="

script:
  - mvn clean verify sonar:sonar -Dsonar.scm.disabled=true -Dsonar.language=java -Dsonar.projectKey=dernasherbrezon_8430ft_exporter

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

