language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "CgcADigSWFgMjytpWDwholUeRo2nLd98mjYXiyG115xqqzxq0UXJXAeE6PQOEpz9SjV4Z3aFkdIR2CKUtuWlzQB442h5McjpvKTQwb0jnPkyeQM24WggBkqYX8vr42ct04amq93XfDKzIoNC1KHZJ7o0DN3HkWpC8D1VRsxetV/cEsQ77dNvlEy7eJYX0SX7JpY1pdQuS7MQPK8Vh24W4M+qnE8XNg9dfbecEXGgs6+URu/6++JRSwRTN4ReljuCBI2NU3/lnYuU/0y+ybkBn4mzuKUfRJBUpkVphWIoJqgXYYqjk9DphIf6FJYGUSdeOBknR4Xx8TNgIEbDIvOf/5/X6EKUVx2Akf11rXwKOgv/fs1iRGHxHSHHe0t4h4sTLu6+BvlUGOkSS+pRt2z/iMFvjQ66TkQTssCMOJ2d0enCvYZEPGaqPzCakGb8LyCCfGv9AA/X5oyVPGXWlO72aM36Co2BCN9eVCHDTez9ttIwBft5t7Iir+ShJNVKaji/jsm+BFmAWWM76glW6JczSxyCiirhec709mDT1hV60v6REiB0gNABcRTSVxgrtpBYK38+TrAdFoKI3Ku5d9XuL0MqJMBRAnt0hpIq+PmjCR9UQ9oVgobqIlUB6Jb7eX3v+kTE+vi4OFAvH+Oj/b7HCY9kff1fhDFueAE00D6GCLE="

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.language=java -Dsonar.projectKey=dernasherbrezon_8430ft_exporter

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

